spring:
  application:
    name: keycloak-auth-service
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm} // authorization server

server:
  port: 8088
  servlet:
    context-path: /auth/api/v1
app:
  keycloak:
    admin:
      clientId: ${KEYCLOAK_ADMIN_CLIENT}
      clientSecret: ${KEYCLOAK_ADMIN_SECRET}
    realm: ${KEYCLOAK_REALM}
    serverUrl: ${KEYCLOAK_SERVER_URL}

logging:
  level:
    org.keycloak: DEBUG
